<?php

return [
    'default_preference' => 'system',
    'fallback_theme' => 'light',
    'preferences' => ['light', 'dark', 'system'],
    'resolved' => ['light', 'dark'],

    'themes' => [
        'light' => [
            'label' => 'Light',
            'tokens' => [
                'surface' => '#F8FAFC',
                'surface-secondary' => '#F1F5F9',
                'elevated' => '#FFFFFF',
                'card' => '#FFFFFF',
                'sidebar' => '#FFFFFF',
                'header' => '#FFFFFF',
                'muted' => '#E2E8F0',
                'border-default' => '#E2E8F0',
                'border-subtle' => 'rgba(15, 23, 42, 0.08)',
                'text-primary' => '#0F172A',
                'text-secondary' => '#475569',
                'text-muted' => '#64748B',
                'overlay' => 'rgba(15, 23, 42, 0.45)',
                'shadow' => '0 8px 24px rgba(15, 23, 42, 0.08)',
                'blur' => '12px',
                'input-bg' => '#FFFFFF',
                'table-stripe' => '#F8FAFC',
                'table-hover' => '#F1F5F9',
                'code-bg' => '#F1F5F9',
                'gradient-soft' => 'linear-gradient(135deg, #F8FAFC 0%, #EEF2FF 100%)',
                'icon-bg' => '#ECFDF5',
                'icon-fg' => '#0B6A39',
            ],
            'rgb' => [
                'surface' => '248 250 252',
                'elevated' => '255 255 255',
                'muted' => '226 232 240',
                'card' => '255 255 255',
            ],
            'charts' => [
                'background' => '#FFFFFF',
                'grid' => '#E2E8F0',
                'labels' => '#64748B',
                'legend' => '#475569',
                'tooltipBg' => '#0F172A',
                'tooltipText' => '#F8FAFC',
                'axis' => '#94A3B8',
                'crosshair' => '#0B6A39',
                'selection' => 'rgba(11, 106, 57, 0.15)',
                'hover' => 'rgba(11, 106, 57, 0.25)',
            ],
            'assets' => [
                'logo' => 'assets/images/originla_logo.png',
                'logo_fallback' => 'assets/images/originla_logo.png',
                'empty.default' => null,
                'empty.wallet' => null,
                'empty.marketplace' => null,
                'empty.dashboard' => null,
            ],
        ],
        'dark' => [
            'label' => 'Dark',
            'tokens' => [
                'surface' => '#0F172A',
                'surface-secondary' => '#111827',
                'elevated' => '#1E293B',
                'card' => 'rgba(30, 41, 59, 0.72)',
                'sidebar' => '#1E293B',
                'header' => 'rgba(30, 41, 59, 0.85)',
                'muted' => '#334155',
                'border-default' => '#334155',
                'border-subtle' => 'rgba(255, 255, 255, 0.1)',
                'text-primary' => '#F1F5F9',
                'text-secondary' => '#94A3B8',
                'text-muted' => '#64748B',
                'overlay' => 'rgba(2, 6, 23, 0.65)',
                'shadow' => '0 8px 32px rgba(0, 0, 0, 0.35)',
                'blur' => '12px',
                'input-bg' => 'rgba(30, 41, 59, 0.55)',
                'table-stripe' => 'rgba(51, 65, 85, 0.35)',
                'table-hover' => 'rgba(51, 65, 85, 0.55)',
                'code-bg' => '#111827',
                'gradient-soft' => 'linear-gradient(135deg, #0F172A 0%, #052e16 100%)',
                'icon-bg' => 'rgba(11, 106, 57, 0.18)',
                'icon-fg' => '#4ade80',
            ],
            'rgb' => [
                'surface' => '15 23 42',
                'elevated' => '30 41 59',
                'muted' => '51 65 85',
                'card' => '30 41 59',
            ],
            'charts' => [
                'background' => '#0F172A',
                'grid' => '#334155',
                'labels' => '#94A3B8',
                'legend' => '#CBD5E1',
                'tooltipBg' => '#1E293B',
                'tooltipText' => '#F8FAFC',
                'axis' => '#64748B',
                'crosshair' => '#16A34A',
                'selection' => 'rgba(22, 163, 74, 0.2)',
                'hover' => 'rgba(22, 163, 74, 0.3)',
            ],
            'assets' => [
                'logo' => 'assets/images/white_originla_logo.png',
                'logo_fallback' => 'assets/images/originla_logo.png',
                'empty.default' => null,
                'empty.wallet' => null,
                'empty.marketplace' => null,
                'empty.dashboard' => null,
            ],
        ],
    ],
];
