<?php

return [
    'user' => [
        [
            'type' => 'link',
            'id' => 'dashboard',
            'label' => 'Dashboard',
            'route' => 'dashboard',
            'match' => ['dashboard'],
            'icon' => 'home',
            'keywords' => ['home', 'overview'],
            'sort' => 10,
        ],
        [
            'type' => 'link',
            'id' => 'kyc',
            'label' => 'KYC',
            'route' => 'dashboard.kyc',
            'match' => ['dashboard.kyc', 'dashboard.kyc.*'],
            'icon' => 'kyc',
            'keywords' => ['identity', 'verification'],
            'sort' => 20,
        ],
        [
            'type' => 'group',
            'id' => 'wallet',
            'label' => 'Wallet',
            'icon' => 'wallet',
            'sort' => 30,
            'children' => [
                ['route' => 'dashboard.wallet', 'match' => ['dashboard.wallet', 'dashboard.wallet.*'], 'label' => 'Wallet', 'icon' => 'wallet', 'keywords' => ['balance', 'funds'], 'sort' => 10],
                ['route' => 'dashboard.deposit.index', 'match' => ['dashboard.deposit.*'], 'label' => 'Deposit', 'icon' => 'deposit', 'keywords' => ['fund', 'bank'], 'sort' => 20],
                ['route' => 'dashboard.crypto-sell.index', 'match' => ['dashboard.crypto-sell.*'], 'label' => 'Sell Crypto', 'icon' => 'bitcoin', 'keywords' => ['otc', 'crypto'], 'sort' => 30],
                ['route' => 'dashboard.withdrawal.index', 'match' => ['dashboard.withdrawal.*'], 'label' => 'Withdraw', 'icon' => 'withdraw', 'keywords' => ['payout', 'cashout'], 'sort' => 40],
                ['route' => 'dashboard.history', 'match' => ['dashboard.history'], 'label' => 'History', 'icon' => 'history', 'keywords' => ['ledger', 'activity'], 'sort' => 50],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'discover',
            'label' => 'Discover',
            'icon' => 'storefront',
            'sort' => 35,
            'children' => [
                ['route' => 'dashboard.discover.marketplace', 'match' => ['dashboard.discover.marketplace', 'dashboard.discover.marketplace.*'], 'label' => 'Marketplace', 'icon' => 'storefront', 'keywords' => ['browse', 'buy', 'listings'], 'sort' => 10],
                ['route' => 'dashboard.discover.services', 'match' => ['dashboard.discover.services', 'dashboard.discover.services.*'], 'label' => 'Services', 'icon' => 'listings', 'keywords' => ['catalog', 'platform', 'buy'], 'sort' => 20],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'marketplace',
            'label' => 'Selling',
            'icon' => 'inventory',
            'sort' => 40,
            'children' => [
                ['route' => 'dashboard.listings', 'match' => ['dashboard.listings', 'dashboard.listings.*'], 'label' => 'My Listings', 'icon' => 'listings', 'keywords' => ['sell', 'products'], 'sort' => 10],
                ['route' => 'dashboard.sales', 'match' => ['dashboard.sales'], 'label' => 'Sales', 'icon' => 'orders', 'keywords' => ['sold', 'delivery'], 'sort' => 15],
                ['route' => 'dashboard.watchlist', 'match' => ['dashboard.watchlist', 'dashboard.watchlist.*'], 'label' => 'Watchlist', 'icon' => 'watchlist', 'keywords' => ['saved', 'favorites'], 'sort' => 20],
                ['route' => 'dashboard.orders', 'match' => ['dashboard.orders', 'dashboard.orders.*'], 'label' => 'Orders', 'icon' => 'orders', 'keywords' => ['purchases', 'buy'], 'sort' => 30],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'inbox',
            'label' => 'Communication',
            'icon' => 'messages',
            'sort' => 50,
            'children' => [
                ['route' => 'dashboard.messages', 'match' => ['dashboard.messages', 'dashboard.messages.*'], 'label' => 'Messages', 'icon' => 'messages', 'keywords' => ['inbox', 'chat'], 'sort' => 10],
                ['route' => 'dashboard.notifications', 'match' => ['dashboard.notifications', 'dashboard.notifications.*'], 'label' => 'Notifications', 'icon' => 'notifications', 'keywords' => ['alerts'], 'sort' => 20],
                ['route' => 'dashboard.support.index', 'match' => ['dashboard.support.*'], 'label' => 'Support', 'icon' => 'support', 'keywords' => ['tickets', 'help'], 'sort' => 30],
            ],
        ],
    ],

    'admin' => [
        [
            'type' => 'link',
            'id' => 'overview',
            'label' => 'Overview',
            'route' => 'admin',
            'match' => ['admin'],
            'icon' => 'home',
            'keywords' => ['home', 'dashboard'],
            'sort' => 5,
        ],
        [
            'type' => 'group',
            'id' => 'operations',
            'label' => 'Operations',
            'icon' => 'users',
            'sort' => 10,
            'children' => [
                ['route' => 'admin.users', 'match' => ['admin.users', 'admin.users.*'], 'label' => 'Users', 'icon' => 'users', 'keywords' => ['members', 'accounts'], 'permission' => 'users.manage', 'sort' => 10],
                ['route' => 'admin.administrators', 'match' => ['admin.administrators', 'admin.administrators.*'], 'label' => 'Administrators', 'icon' => 'verified', 'keywords' => ['admins', 'staff'], 'permission' => 'admins.manage', 'sort' => 20],
                ['route' => 'admin.kyc', 'match' => ['admin.kyc', 'admin.kyc.*'], 'label' => 'KYC', 'icon' => 'kyc', 'keywords' => ['identity', 'verification'], 'permission' => 'compliance.manage', 'sort' => 30],
                ['route' => 'admin.tickets', 'match' => ['admin.tickets', 'admin.tickets.*'], 'label' => 'Support', 'icon' => 'support', 'keywords' => ['help', 'tickets'], 'permission' => 'support.manage', 'sort' => 40],
                ['route' => 'admin.audit-logs', 'match' => ['admin.audit-logs', 'admin.audit-logs.*'], 'label' => 'Audit Logs', 'icon' => 'audit', 'keywords' => ['logs', 'activity'], 'permission' => 'system.manage', 'sort' => 50],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'platform-catalog',
            'label' => 'Platform Catalog',
            'icon' => 'storefront',
            'sort' => 20,
            'children' => [
                ['route' => 'admin.service-categories', 'match' => ['admin.service-categories', 'admin.service-categories.*'], 'label' => 'Service Categories', 'icon' => 'grid', 'keywords' => ['catalog', 'categories'], 'permission' => 'catalog.manage', 'sort' => 10],
                ['route' => 'admin.services', 'match' => ['admin.services', 'admin.services.*'], 'label' => 'Services', 'icon' => 'listings', 'keywords' => ['catalog', 'services', 'types'], 'permission' => 'catalog.manage', 'sort' => 20],
                ['route' => 'admin.platform-products', 'match' => ['admin.platform-products', 'admin.platform-products.*'], 'label' => 'Products', 'icon' => 'storefront', 'keywords' => ['prod', 'catalog', 'products'], 'permission' => 'catalog.manage', 'sort' => 30],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'marketplace',
            'label' => 'Marketplace',
            'icon' => 'inventory',
            'sort' => 30,
            'children' => [
                ['route' => 'admin.marketplace-categories', 'match' => ['admin.marketplace-categories', 'admin.marketplace-categories.*'], 'label' => 'Marketplace Categories', 'icon' => 'grid', 'keywords' => ['categories', 'market'], 'permission' => 'catalog.manage', 'sort' => 10],
                ['route' => 'admin.marketplace-products', 'match' => ['admin.marketplace-products', 'admin.marketplace-products.*'], 'label' => 'Marketplace Products', 'icon' => 'storefront', 'keywords' => ['products', 'market', 'types'], 'permission' => 'catalog.manage', 'sort' => 20],
                ['route' => 'admin.listings', 'match' => ['admin.listings', 'admin.listings.*'], 'label' => 'Marketplace Listings', 'icon' => 'listings', 'keywords' => ['marketplace', 'listings', 'review', 'pending'], 'permission' => 'catalog.manage', 'sort' => 30],
                ['route' => 'admin.escrows', 'match' => ['admin.escrows', 'admin.escrows.*'], 'label' => 'Escrows', 'icon' => 'lock', 'keywords' => ['release', 'refund'], 'permission' => 'finance.manage', 'sort' => 40],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'crypto-exchange',
            'label' => 'Crypto Exchange',
            'icon' => 'bitcoin',
            'sort' => 40,
            'children' => [
                ['route' => 'admin.fundings', 'match' => ['admin.fundings', 'admin.fundings.*'], 'label' => 'Deposits', 'icon' => 'deposit', 'keywords' => ['fundings', 'bank'], 'permission' => 'finance.manage', 'sort' => 10],
                ['route' => 'admin.crypto-sells', 'match' => ['admin.crypto-sells', 'admin.crypto-sells.*'], 'label' => 'Sell Requests', 'icon' => 'bitcoin', 'keywords' => ['otc', 'crypto'], 'permission' => 'finance.manage', 'sort' => 20],
                ['route' => 'admin.withdrawals', 'match' => ['admin.withdrawals', 'admin.withdrawals.*'], 'label' => 'Withdrawals', 'icon' => 'withdraw', 'keywords' => ['payouts'], 'permission' => 'finance.manage', 'sort' => 30],
                ['route' => 'admin.exchange-rates', 'match' => ['admin.exchange-rates', 'admin.exchange-rates.*'], 'label' => 'Exchange Rates', 'icon' => 'bitcoin', 'keywords' => ['rates', 'fx', 'crypto'], 'permission' => 'catalog.manage', 'sort' => 40],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'finance',
            'label' => 'Finance',
            'icon' => 'wallet',
            'sort' => 50,
            'children' => [
                ['route' => 'admin.wallet-adjustment', 'match' => ['admin.wallet-adjustment', 'admin.wallet-adjustment.*'], 'label' => 'Wallet Adjustments', 'icon' => 'wallet-adjust', 'keywords' => ['credit', 'debit', 'adjust'], 'permission' => 'finance.manage', 'sort' => 10],
                ['route' => 'admin.transactions', 'match' => ['admin.transactions', 'admin.transactions.*'], 'label' => 'Transactions', 'icon' => 'transactions', 'keywords' => ['ledger', 'history'], 'permission' => 'finance.manage', 'sort' => 20],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'system',
            'label' => 'System',
            'icon' => 'settings',
            'sort' => 60,
            'children' => [
                ['route' => 'admin.analytics', 'match' => ['admin.analytics', 'admin.analytics.*'], 'label' => 'Analytics', 'icon' => 'analytics', 'keywords' => ['reports', 'metrics'], 'permission' => 'analytics.view', 'sort' => 10],
                ['route' => 'admin.monitoring', 'match' => ['admin.monitoring', 'admin.monitoring.*'], 'label' => 'Monitoring', 'icon' => 'audit', 'keywords' => ['health', 'heartbeat', 'system'], 'permission' => 'system.manage', 'sort' => 12],
                ['route' => 'admin.media', 'match' => ['admin.media', 'admin.media.*'], 'label' => 'Media Library', 'icon' => 'listings', 'keywords' => ['media', 'images', 'upload'], 'permission' => 'system.manage', 'sort' => 15],
                ['route' => 'admin.settings', 'match' => ['admin.settings', 'admin.settings.*'], 'label' => 'Settings', 'icon' => 'settings', 'keywords' => ['platform', 'config'], 'permission' => 'system.manage', 'sort' => 20],
            ],
        ],
    ],
];
