<?php

return [
    'user' => [
        [
            'type' => 'link',
            'id' => 'dashboard',
            'label' => 'Dashboard',
            'route' => 'dashboard',
            'match' => ['dashboard'],
            'icon' => 'home',
            'keywords' => ['home', 'overview'],
            'sort' => 10,
        ],
        [
            'type' => 'group',
            'id' => 'services',
            'label' => 'Services',
            'icon' => 'listings',
            'sort' => 20,
            'children' => [
                ['route' => 'dashboard.services', 'match' => ['dashboard.services', 'dashboard.services.*', 'dashboard.discover.services', 'dashboard.discover.services.*'], 'label' => 'Browse', 'icon' => 'listings', 'keywords' => ['catalog', 'platform', 'buy', 'services'], 'sort' => 10],
                ['route' => 'dashboard.my-tools', 'url' => '/dashboard/my-tools', 'match' => ['dashboard.my-tools', 'dashboard.my-tools.*'], 'label' => 'My Tools', 'icon' => 'listings', 'keywords' => ['websites', 'tools', 'owned'], 'sort' => 15],
                ['route' => 'dashboard.service-orders', 'match' => ['dashboard.service-orders', 'dashboard.service-orders.*'], 'label' => 'Orders', 'icon' => 'orders', 'keywords' => ['purchases', 'platform'], 'sort' => 20],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'marketplace',
            'label' => 'Marketplace',
            'icon' => 'storefront',
            'sort' => 30,
            'children' => [
                ['route' => 'dashboard.marketplace', 'match' => ['dashboard.marketplace', 'dashboard.marketplace.*', 'dashboard.discover.marketplace', 'dashboard.discover.marketplace.*'], 'label' => 'Browse', 'icon' => 'storefront', 'keywords' => ['buy', 'listings', 'browse'], 'sort' => 10],
                ['route' => 'dashboard.listings', 'match' => ['dashboard.listings', 'dashboard.listings.*'], 'label' => 'My Listings', 'icon' => 'listings', 'keywords' => ['sell', 'products'], 'sort' => 20],
                ['route' => 'dashboard.sales', 'match' => ['dashboard.sales'], 'label' => 'Sales', 'icon' => 'orders', 'keywords' => ['sold', 'delivery'], 'sort' => 30],
                ['route' => 'dashboard.watchlist', 'match' => ['dashboard.watchlist', 'dashboard.watchlist.*'], 'label' => 'Watchlist', 'icon' => 'watchlist', 'keywords' => ['saved', 'favorites'], 'sort' => 40],
                ['route' => 'dashboard.messages', 'match' => ['dashboard.messages', 'dashboard.messages.*'], 'label' => 'Escrow Conversations', 'icon' => 'messages', 'keywords' => ['escrow', 'chat', 'order'], 'sort' => 50],
                ['route' => 'dashboard.orders', 'match' => ['dashboard.orders', 'dashboard.orders.*'], 'label' => 'Orders', 'icon' => 'shopping-bag', 'keywords' => ['purchases', 'buy', 'marketplace'], 'sort' => 60],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'wallet',
            'label' => 'Wallet',
            'icon' => 'wallet',
            'sort' => 15,
            'children' => [
                ['route' => 'dashboard.wallet', 'match' => ['dashboard.wallet', 'dashboard.wallet.*'], 'label' => 'Wallet', 'icon' => 'wallet', 'keywords' => ['balance', 'funds'], 'sort' => 10],
                ['route' => 'dashboard.deposit.index', 'match' => ['dashboard.deposit.*'], 'label' => 'Deposit', 'icon' => 'deposit', 'keywords' => ['fund', 'bank'], 'sort' => 20],
                ['route' => 'dashboard.withdrawal.index', 'match' => ['dashboard.withdrawal.*'], 'label' => 'Withdraw', 'icon' => 'withdraw', 'keywords' => ['payout', 'cashout'], 'sort' => 30],
                ['route' => 'dashboard.history', 'match' => ['dashboard.history'], 'label' => 'History', 'icon' => 'history', 'keywords' => ['ledger', 'activity'], 'sort' => 40],
            ],
        ],
        [
            'type' => 'link',
            'id' => 'exchange',
            'label' => 'Sell Crypto',
            'route' => 'dashboard.exchange',
            'match' => ['dashboard.exchange', 'dashboard.crypto-sell.*'],
            'icon' => 'bitcoin',
            'keywords' => ['crypto', 'sell', 'otc', 'exchange'],
            'sort' => 50,
        ],
        [
            'type' => 'link',
            'id' => 'support',
            'label' => 'Support',
            'route' => 'dashboard.support.index',
            'match' => ['dashboard.support.*'],
            'icon' => 'support',
            'keywords' => ['tickets', 'help', 'contact'],
            'sort' => 60,
        ],
        [
            'type' => 'link',
            'id' => 'settings',
            'label' => 'Settings',
            'route' => 'dashboard.account.profile',
            'match' => ['dashboard.account.*'],
            'icon' => 'settings',
            'keywords' => ['profile', 'account', 'security', 'kyc', 'preferences'],
            'sort' => 70,
        ],
    ],
    'admin' => [
        [
            'type' => 'link',
            'id' => 'overview',
            'label' => 'Overview',
            'route' => 'admin',
            'match' => ['admin'],
            'icon' => 'home',
            'keywords' => ['home', 'dashboard'],
            'sort' => 5,
        ],
        [
            'type' => 'group',
            'id' => 'operations',
            'label' => 'Operations',
            'icon' => 'users',
            'sort' => 10,
            'children' => [
                ['route' => 'admin.users', 'match' => ['admin.users', 'admin.users.*'], 'label' => 'Users', 'icon' => 'users', 'keywords' => ['members', 'accounts'], 'permission' => 'users.manage', 'sort' => 10],
                ['route' => 'admin.administrators', 'match' => ['admin.administrators', 'admin.administrators.*'], 'label' => 'Administrators', 'icon' => 'verified', 'keywords' => ['admins', 'staff'], 'permission' => 'admins.manage', 'sort' => 20],
                ['route' => 'admin.kyc', 'match' => ['admin.kyc', 'admin.kyc.*'], 'label' => 'KYC', 'icon' => 'kyc', 'keywords' => ['identity', 'verification'], 'permission' => 'compliance.manage', 'sort' => 30],
                ['route' => 'admin.tickets', 'match' => ['admin.tickets', 'admin.tickets.*'], 'label' => 'Support', 'icon' => 'support', 'keywords' => ['help', 'tickets'], 'permission' => 'support.manage', 'sort' => 40],
                ['route' => 'admin.fees-limits', 'match' => ['admin.fees-limits', 'admin.fees-limits.*'], 'label' => 'Fees & Limits', 'icon' => 'paid', 'keywords' => ['fees', 'limits', 'deposit', 'withdrawal'], 'permission' => 'fees.manage', 'sort' => 45],
                ['route' => 'admin.audit-logs', 'match' => ['admin.audit-logs', 'admin.audit-logs.*'], 'label' => 'Audit Logs', 'icon' => 'audit', 'keywords' => ['logs', 'activity'], 'permission' => 'system.manage', 'sort' => 50],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'platform-catalog',
            'label' => 'Platform Catalog',
            'icon' => 'storefront',
            'sort' => 20,
            'children' => [
                ['route' => 'admin.service-categories', 'match' => ['admin.service-categories', 'admin.service-categories.*'], 'label' => 'Service Categories', 'icon' => 'grid', 'keywords' => ['catalog', 'categories'], 'permission' => 'catalog.manage', 'sort' => 10],
                ['route' => 'admin.services', 'match' => ['admin.services', 'admin.services.*'], 'label' => 'Services', 'icon' => 'listings', 'keywords' => ['catalog', 'services', 'types'], 'permission' => 'catalog.manage', 'sort' => 20],
                ['route' => 'admin.platform-products', 'match' => ['admin.platform-products', 'admin.platform-products.*'], 'label' => 'Products', 'icon' => 'storefront', 'keywords' => ['prod', 'catalog', 'products'], 'permission' => 'catalog.manage', 'sort' => 30],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'marketplace',
            'label' => 'Marketplace',
            'icon' => 'inventory',
            'sort' => 30,
            'children' => [
                ['route' => 'admin.listings', 'match' => ['admin.listings', 'admin.listings.*'], 'label' => 'Marketplace Listings', 'icon' => 'listings', 'keywords' => ['marketplace', 'listings', 'review', 'pending'], 'permission' => 'catalog.manage', 'sort' => 10],
                ['route' => 'admin.marketplace-categories', 'match' => ['admin.marketplace-categories', 'admin.marketplace-categories.*'], 'label' => 'Marketplace Categories', 'icon' => 'grid', 'keywords' => ['categories', 'market'], 'permission' => 'catalog.manage', 'sort' => 20],
                ['route' => 'admin.marketplace-products', 'match' => ['admin.marketplace-products', 'admin.marketplace-products.*'], 'label' => 'Marketplace Products', 'icon' => 'storefront', 'keywords' => ['products', 'market', 'types'], 'permission' => 'catalog.manage', 'sort' => 30],
                ['route' => 'admin.escrows', 'match' => ['admin.escrows', 'admin.escrows.*'], 'label' => 'Escrows', 'icon' => 'lock', 'keywords' => ['release', 'refund'], 'permission' => 'finance.manage', 'sort' => 40],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'crypto-exchange',
            'label' => 'Crypto Exchange',
            'icon' => 'bitcoin',
            'sort' => 40,
            'children' => [
                ['route' => 'admin.crypto-sells', 'match' => ['admin.crypto-sells', 'admin.crypto-sells.*'], 'label' => 'Sell Requests', 'icon' => 'bitcoin', 'keywords' => ['otc', 'crypto'], 'permission' => 'finance.manage', 'sort' => 10],
                ['route' => 'admin.incoming-deposits', 'match' => ['admin.incoming-deposits', 'admin.incoming-deposits.*'], 'label' => 'Incoming Deposits', 'icon' => 'deposit', 'keywords' => ['blockchain', 'monitor', 'tx'], 'permission' => 'finance.manage', 'sort' => 15],
                ['route' => 'admin.crypto-wallets', 'match' => ['admin.crypto-wallets', 'admin.crypto-wallets.*'], 'label' => 'Deposit Wallets', 'icon' => 'wallet', 'keywords' => ['address', 'qr', 'treasury'], 'permission' => 'finance.manage', 'sort' => 18],
                ['route' => 'admin.crypto-wallets.treasury', 'match' => ['admin.crypto-wallets.treasury'], 'label' => 'Treasury Inventory', 'icon' => 'wallet', 'keywords' => ['holdings', 'inventory'], 'permission' => 'finance.manage', 'sort' => 19],
                ['route' => 'admin.otc-pricing', 'match' => ['admin.otc-pricing', 'admin.otc-pricing.*'], 'label' => 'OTC Pricing', 'icon' => 'bitcoin', 'keywords' => ['otc', 'market', 'spread', 'buy rate', 'ngn', 'usd', 'tolerance', 'quote', 'wallet pool', 'matching'], 'permission' => 'finance.manage', 'sort' => 22],
                ['route' => 'admin.exchange-rates', 'match' => ['admin.exchange-rates', 'admin.exchange-rates.*'], 'label' => 'Coin Catalog', 'icon' => 'bitcoin', 'keywords' => ['rates', 'fx', 'crypto', 'coins', 'networks'], 'permission' => 'catalog.manage', 'sort' => 30],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'finance',
            'label' => 'Finance',
            'icon' => 'wallet',
            'sort' => 50,
            'children' => [
                ['route' => 'admin.fundings', 'match' => ['admin.fundings', 'admin.fundings.*'], 'label' => 'Deposits', 'icon' => 'deposit', 'keywords' => ['fundings', 'bank'], 'permission' => 'finance.manage', 'sort' => 10],
                ['route' => 'admin.withdrawals', 'match' => ['admin.withdrawals', 'admin.withdrawals.*'], 'label' => 'Withdrawals', 'icon' => 'withdraw', 'keywords' => ['payouts'], 'permission' => 'finance.manage', 'sort' => 20],
                ['route' => 'admin.reconciliation', 'match' => ['admin.reconciliation', 'admin.reconciliation.*'], 'label' => 'Reconciliation', 'icon' => 'audit', 'keywords' => ['monnify', 'webhooks', 'fix'], 'permission' => 'finance.manage', 'sort' => 25],
                ['route' => 'admin.wallet-adjustment', 'match' => ['admin.wallet-adjustment', 'admin.wallet-adjustment.*'], 'label' => 'Wallet Adjustments', 'icon' => 'wallet-adjust', 'keywords' => ['credit', 'debit', 'adjust'], 'permission' => 'finance.manage', 'sort' => 30],
                ['route' => 'admin.transactions', 'match' => ['admin.transactions', 'admin.transactions.*'], 'label' => 'Transactions', 'icon' => 'transactions', 'keywords' => ['ledger', 'history'], 'permission' => 'finance.manage', 'sort' => 40],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'system',
            'label' => 'System',
            'icon' => 'settings',
            'sort' => 60,
            'children' => [
                ['route' => 'admin.analytics', 'match' => ['admin.analytics', 'admin.analytics.*'], 'label' => 'Analytics', 'icon' => 'analytics', 'keywords' => ['reports', 'metrics'], 'permission' => 'analytics.view', 'sort' => 10],
                ['route' => 'admin.monitoring', 'match' => ['admin.monitoring', 'admin.monitoring.*'], 'label' => 'Monitoring', 'icon' => 'audit', 'keywords' => ['health', 'heartbeat', 'system'], 'permission' => 'system.manage', 'sort' => 12],
                ['route' => 'admin.media', 'match' => ['admin.media', 'admin.media.*'], 'label' => 'Media Library', 'icon' => 'listings', 'keywords' => ['media', 'images', 'upload'], 'permission' => 'system.manage', 'sort' => 15],
                ['route' => 'admin.settings', 'match' => ['admin.settings', 'admin.settings.*'], 'label' => 'Settings', 'icon' => 'settings', 'keywords' => ['platform', 'config'], 'permission' => 'system.manage', 'sort' => 20],
                ['route' => 'admin.site-integrations', 'url' => '/admin/site-integrations', 'match' => ['admin.site-integrations', 'admin.site-integrations.*'], 'label' => 'Demo Site Integrate', 'icon' => 'listings', 'keywords' => ['demo', 'sso', 'integration', 'api', 'merchant'], 'permission' => 'catalog.manage', 'sort' => 21],
                ['route' => 'admin.domain-providers', 'url' => '/admin/domain-providers', 'match' => ['admin.domain-providers', 'admin.domain-providers.*'], 'label' => 'Domain providers', 'icon' => 'grid', 'keywords' => ['domain', 'namecom', 'registrar', 'reseller'], 'permission' => 'system.manage', 'sort' => 22],
                ['route' => 'admin.blockchain-monitoring', 'match' => ['admin.blockchain-monitoring', 'admin.blockchain-monitoring.*'], 'label' => 'Blockchain Monitoring', 'icon' => 'bitcoin', 'keywords' => ['crypto', 'explorer', 'deposit', 'etherscan', 'tron', 'blockchain'], 'permission' => 'system.manage', 'sort' => 22],
                ['route' => 'admin.tracking', 'match' => ['admin.tracking', 'admin.tracking.*'], 'label' => 'Marketing & Tracking', 'icon' => 'analytics', 'keywords' => ['gtm', 'pixel', 'scripts', 'clarity', 'ga'], 'permission' => 'system.manage', 'sort' => 23],
            ],
        ],
    ],
];
