<?php

return [
    'user' => [
        ['route' => 'dashboard', 'label' => 'Dashboard', 'icon' => 'home'],
        ['route' => 'dashboard.kyc', 'label' => 'KYC', 'icon' => 'kyc'],
        ['route' => 'dashboard.wallet', 'label' => 'Wallet', 'icon' => 'wallet'],
        ['route' => 'dashboard.deposit.index', 'label' => 'Deposit', 'icon' => 'deposit'],
        ['route' => 'dashboard.crypto-sell.index', 'label' => 'Sell Crypto', 'icon' => 'bitcoin'],
        ['route' => 'dashboard.withdrawal.index', 'label' => 'Withdraw', 'icon' => 'withdraw'],
        ['route' => 'dashboard.history', 'label' => 'History', 'icon' => 'history'],
        ['route' => 'dashboard.listings', 'label' => 'My Listings', 'icon' => 'listings'],
        ['route' => 'dashboard.watchlist', 'label' => 'Watchlist', 'icon' => 'watchlist'],
        ['route' => 'dashboard.orders', 'label' => 'Orders', 'icon' => 'orders'],
        ['route' => 'dashboard.notifications', 'label' => 'Notifications', 'icon' => 'notifications'],
        ['route' => 'dashboard.support.index', 'label' => 'Support', 'icon' => 'support'],
        ['route' => 'dashboard.messages', 'label' => 'Messages', 'icon' => 'messages'],
    ],

    'admin' => [
        ['route' => 'admin', 'label' => 'Overview', 'icon' => 'dashboard'],
        ['route' => 'admin.kyc', 'label' => 'KYC Review', 'icon' => 'kyc'],
        ['route' => 'admin.fundings', 'label' => 'Deposits', 'icon' => 'deposit'],
        ['route' => 'admin.crypto-sells', 'label' => 'Crypto Sells', 'icon' => 'bitcoin'],
        ['route' => 'admin.withdrawals', 'label' => 'Withdrawals', 'icon' => 'withdraw'],
        ['route' => 'admin.escrows', 'label' => 'Escrows', 'icon' => 'lock'],
        ['route' => 'admin.users', 'label' => 'Users', 'icon' => 'users'],
        ['route' => 'admin.listings.pending', 'label' => 'Listings Review', 'icon' => 'inventory'],
        ['route' => 'admin.platform-products', 'label' => 'Platform Products', 'icon' => 'storefront'],
        ['route' => 'admin.platform-categories', 'label' => 'Platform Categories', 'icon' => 'grid'],
        ['route' => 'admin.catalog-pages', 'label' => 'Catalog Pages', 'icon' => 'listings'],
        ['route' => 'admin.marketplace-categories', 'label' => 'Market Categories', 'icon' => 'listings'],
        ['route' => 'admin.exchange-rates', 'label' => 'Exchange Rates', 'icon' => 'bitcoin'],
        ['route' => 'admin.transactions', 'label' => 'Transactions', 'icon' => 'transactions'],
        ['route' => 'admin.tickets', 'label' => 'Support Tickets', 'icon' => 'support'],
        ['route' => 'admin.wallet-adjustment', 'label' => 'Wallet Adjust', 'icon' => 'wallet-adjust'],
        ['route' => 'admin.settings', 'label' => 'Settings', 'icon' => 'settings'],
        ['route' => 'admin.audit-logs', 'label' => 'Audit Logs', 'icon' => 'audit'],
        ['route' => 'admin.analytics', 'label' => 'Analytics', 'icon' => 'analytics'],
    ],
];
